### ISSUE TITLE
Getting an `assert iface_name in self.written_types, iface_name` when trying to generate the schema for DatahubAPI

### ISSUE THREAD

**Issue by luisvicentesanchez** [profusion/sgqlc#189] opened 2022-02-15 13:45 UTC
I'm getting the following error when I try to generate the schema for the Datahub GraphQL API:

```
  File "/*******/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/*******/lib/python3.9/site-packages/sgqlc/codegen/__init__.py", line 130, in main
    args.func(args)
  File "/*******/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 681, in handle_command
    gen.write()
  File "/*******/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 164, in write
    self.write_types()
  File "/*******/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 261, in write_types
    mapped(t)
  File "/*******/lib/python3.9/site-packages/sgqlc/codegen/schema.py", line 483, in write_type_object
    assert iface_name in self.written_types, iface_name
AssertionError: EntityWithRelationships
```

The interface is the following https://datahubproject.io/docs/graphql/interfaces#entitywithrelationships

Is this error related to the order in which the content of the schema is processed? Is there anything I can do to fix it?

**Comment by luisvicentesanchez** [comment] 2022-02-15 15:59
It seems that the problem here is indeed the ordering. I commented https://github.com/profusion/sgqlc/blob/master/sgqlc/codegen/schema.py#L483 and the codegen can create both the schema and operations. When I try to use the operations I get an error like:

```
Traceback (most recent call last):
  File "/***********/testing.py", line 2, in <module>
    import acryl_datahub_schema
  File "/***********/datahub_schema.py", line 4490, in <module>
    class Chart(sgqlc.types.Type, EntityWithRelationships, Entity):
NameError: name 'EntityWithRelationships' is not defined
```

**Comment by barbieri** [comment] 2022-02-15 17:54
Hum... I'll need some time to investigate it properly, but removing the assertion is not correct (because it will cause a runtime error as you spotted).

Meanwhile, if you can investigate yourself, see if the ordering issue is caused by a dependency cycle or just a missing "topo-sort"... I don't recall if I added some topology sort based on the usage, trusting "the input is already sorted". A quick way to check is reorder the introspection JSON and move the `EntityWithRelationships` before its users.

**Comment by luisvicentesanchez** [comment] 2022-02-15 17:56
Yes, I just removed the assertion just to  "preview" how the library would fit in our use case. I will try to re-order the JSON and I will let you know if that solves the problem.

**Comment by Evgenus** [comment] 2022-07-22 21:33
any update on this?

**Comment by joegoldbeck** [comment] 2022-09-07 20:13
Ran into this as well. Re-ordering types to move `EntityWithRelationships` to the very top of `types` and then using the code from #209 fixes it for me :)

ty @Evgenus !

**Comment by benmosher** [comment] 2022-11-17 19:57
I think this is a quirk resulting from optimizations within Python's list sort. 

FWIW: I added this locally to sort _all_ interfaces ahead of everything else, and it fixes it for me:

```py
    # fields without interfaces first, then order the interface
    # implementor after the interface declaration
    def depend_cmp(a, b):
        if a["kind"] != b["kind"]:
            if a["kind"] == "INTERFACE":
                return -1
            elif b["kind"] == "INTERFACE":
                return 1
```

**Comment by barbieri** [comment] 2022-12-05 18:33
merged, pleas reopen if still an issue

**Closed** 2022-12-05 18:32 UTC
Labels: bug
