### ISSUE TITLE
validate_required_arguments fails if the variable and argument name are different

### ISSUE THREAD

**Issue by marcown** [profusion/sgqlc#144] opened 2021-04-14 21:04 UTC
Hey there,

I have to define an operation in the following way:

```graphql
mutation DeleteProject($ids: [String!]!){
  cascadeDeleteProjects(projectIds: $ids)
}
```

The mutation cascadeDeleteProjects has no named returns / a single value return, thus no {} brackets after cascadeDeleteProjects(...).

But I get the following error generating the client:

```sh
Traceback (most recent call last):
  File "/home/markus/.local/bin/sgqlc-codegen", line 8, in <module>
    sys.exit(main())
  File "/home/markus/.local/lib/python3.9/site-packages/sgqlc/codegen/__init__.py", line 51, in main
    args.func(args)
  File "/home/markus/.local/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 746, in handle_command
    gen.write()
  File "/home/markus/.local/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 628, in write
    self.write_operations()
  File "/home/markus/.local/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 645, in write_operations
    self.write_operation(source)
  File "/home/markus/.local/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 655, in write_operation
    for kind, name, code in visit(gql, visitor):
  File "/home/markus/.local/lib/python3.9/site-packages/graphql/language/visitor.py", line 314, in visit
    result = visit_fn(node, key, parent, path, ancestors)
  File "/home/markus/.local/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 470, in leave_field
    self.validate_required_arguments(node)
  File "/home/markus/.local/lib/python3.9/site-packages/sgqlc/codegen/operation.py", line 464, in validate_required_arguments
    raise ValueError(
ValueError: missing required arguments: projectIds at operations/operations.graphql:93:3

```

it works with all my other mutations returning a named struct

**Comment by barbieri** [comment] 2021-04-14 21:10
Are you sure this is related? The stack trace and the message looks like you're not passing `projectIds` somehow (which is weird, because you are)

not sure if you tried with the latest 12.2 that I just released, but it does include a fix for argument variables, maybe it fixes this issue?

**Comment by marcown** [comment] 2021-04-15 04:28
No, I'm not sure. It does not work with 12.2 either. I get the same error.

**Comment by marcown** [comment] 2021-04-15 07:20
@barbieri 

I had to rename it to

mutation DeleteProject($projectIds: [String!]!){
  cascadeDeleteProjects(projectIds: $projectIds)
}

so the variable id had to be named $projectIds, now it works

**Comment by barbieri** [comment] 2021-04-15 12:52
hum... so this is actually wrong in our side, the name of the variable has nothing to do with the argument... I'll take a look. Thanks for noticing

**Comment by barbieri** [comment] 2021-04-15 12:53
btw, I'll rewrite the issue title to reflect so

**Comment by barbieri** [comment] 2021-04-15 13:04
actually this seems to be a duplicate of #133

**Closed** 2021-04-15 18:09 UTC

**Comment by barbieri** [comment] 2021-04-15 21:41
could you test #145?
